"""
Turn the offline CSVs in data/ into one BigQuery SQL script (sql/00_load_crm.sql).

Why SQL instead of the console's CSV upload: the tables are tiny, the script is
re-runnable, and it lives in git next to the analysis queries. It creates the
`crm` dataset (same US location as the GA4 export) and one table per CSV using
CREATE OR REPLACE TABLE ... AS SELECT * FROM UNNEST([STRUCT(...), ...]).

Usage:
    python scripts/make_crm_sql.py            # writes sql/00_load_crm.sql
"""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA, SQL = ROOT / "data", ROOT / "sql"
PROJECT, DATASET = "toyomo-ga4", "crm"

# column -> BigQuery type; anything not listed is STRING
TYPES = {
    "price": "INT64", "satisfaction": "INT64",
    "first_seen": "DATE", "test_drive_date": "DATE", "contract_date": "DATE",
}
TABLES = ["customers", "dealer_test_drives", "contracts"]


def literal(col: str, value: str) -> str:
    t = TYPES.get(col, "STRING")
    if value == "":
        return f"CAST(NULL AS {t})"
    if t == "INT64":
        return value
    if t == "DATE":
        return f"DATE '{value}'"
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def table_sql(name: str) -> str:
    with (DATA / f"{name}.csv").open(encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    cols = list(rows[0].keys())
    structs = []
    for r in rows:
        fields = ", ".join(f"{literal(c, r[c])} AS {c}" for c in cols)
        structs.append(f"  STRUCT({fields})")
    return (
        f"CREATE OR REPLACE TABLE `{PROJECT}.{DATASET}.{name}` AS\n"
        f"SELECT * FROM UNNEST([\n" + ",\n".join(structs) + "\n]);\n"
    )


def main():
    parts = [
        "-- 00. Load the fake dealer/CRM data into BigQuery (generated by scripts/make_crm_sql.py)\n"
        "-- Run the whole script once in the BigQuery console; re-running replaces the tables.\n\n"
        f"CREATE SCHEMA IF NOT EXISTS `{PROJECT}.{DATASET}` OPTIONS (location = 'US');\n"
    ]
    for name in TABLES:
        parts.append(table_sql(name))
    out = SQL / "00_load_crm.sql"
    out.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
