-- 00. Load the fake dealer/CRM data into BigQuery (generated by scripts/make_crm_sql.py)
-- Run the whole script once in the BigQuery console; re-running replaces the tables.

CREATE SCHEMA IF NOT EXISTS `toyomo-ga4.crm` OPTIONS (location = 'US');

CREATE OR REPLACE TABLE `toyomo-ga4.crm.customers` AS
SELECT * FROM UNNEST([
  STRUCT('C69CE05961B9B' AS customer_id, 'seoul' AS region, '서울 강남 전시장' AS home_dealer, '30s' AS age_band, 'F' AS gender, 'web_lead' AS acquired_via, DATE '2026-09-28' AS first_seen, 'LMUKY5ZZX0YLC' AS web_lead_id, 'instagram' AS first_touch_source),
  STRUCT('C7B6B8E0B64FA' AS customer_id, 'incheon' AS region, '인천 송도 전시장' AS home_dealer, '20s' AS age_band, 'M' AS gender, 'web_lead' AS acquired_via, DATE '2026-09-28' AS first_seen, 'LMUKY6CUBAD8F' AS web_lead_id, 'kakao' AS first_touch_source),
  STRUCT('CD9C798D966D5' AS customer_id, 'seoul' AS region, '서울 강남 전시장' AS home_dealer, '40s' AS age_band, 'F' AS gender, 'web_lead' AS acquired_via, DATE '2026-09-28' AS first_seen, 'LMUKY8V339I56' AS web_lead_id, 'youtube' AS first_touch_source),
  STRUCT('CF80E360C12E2' AS customer_id, 'daegu' AS region, '대구 수성 전시장' AS home_dealer, '40s' AS age_band, 'M' AS gender, 'web_lead' AS acquired_via, DATE '2026-09-28' AS first_seen, 'LMUKYAF4RZ2CA' AS web_lead_id, 'google' AS first_touch_source),
  STRUCT('C712BAF74BDE1' AS customer_id, 'daegu' AS region, '대구 수성 전시장' AS home_dealer, '30s' AS age_band, 'M' AS gender, 'web_lead' AS acquired_via, DATE '2026-09-28' AS first_seen, 'LMUKYB8AQIHXV' AS web_lead_id, 'naver' AS first_touch_source),
  STRUCT('C57455088AC05' AS customer_id, 'daegu' AS region, '대구 수성 전시장' AS home_dealer, '40s' AS age_band, 'M' AS gender, 'web_lead' AS acquired_via, DATE '2026-09-28' AS first_seen, 'LMUKYBYYVWIY5' AS web_lead_id, 'naver' AS first_touch_source),
  STRUCT('CC962AD4317D4' AS customer_id, 'busan' AS region, '부산 해운대 전시장' AS home_dealer, '40s' AS age_band, 'M' AS gender, 'web_lead' AS acquired_via, DATE '2026-09-29' AS first_seen, 'LMULYNJLMXIKZ' AS web_lead_id, 'instagram' AS first_touch_source),
  STRUCT('CB29B4D6B6DE9' AS customer_id, 'gyeonggi' AS region, '분당 판교 전시장' AS home_dealer, '20s' AS age_band, 'F' AS gender, 'web_lead' AS acquired_via, DATE '2026-09-29' AS first_seen, 'LMULYNWDHRLZ2' AS web_lead_id, 'naver' AS first_touch_source),
  STRUCT('C25D19B395E2E' AS customer_id, 'incheon' AS region, '인천 송도 전시장' AS home_dealer, '20s' AS age_band, 'F' AS gender, 'web_lead' AS acquired_via, DATE '2026-09-29' AS first_seen, 'LMULYRH678G9D' AS web_lead_id, 'naver' AS first_touch_source),
  STRUCT('CB3BF0B266708' AS customer_id, 'gwangju' AS region, '광주 상무 전시장' AS home_dealer, '40s' AS age_band, 'M' AS gender, 'web_lead' AS acquired_via, DATE '2026-09-29' AS first_seen, 'LMULYRRXH7SQH' AS web_lead_id, 'naver' AS first_touch_source),
  STRUCT('C6D74C3C359D3' AS customer_id, 'gyeonggi' AS region, '분당 판교 전시장' AS home_dealer, '20s' AS age_band, 'F' AS gender, 'web_lead' AS acquired_via, DATE '2026-09-29' AS first_seen, 'LMULYS50X2UW3' AS web_lead_id, 'youtube' AS first_touch_source),
  STRUCT('C4053A83827FE' AS customer_id, 'gyeonggi' AS region, '분당 판교 전시장' AS home_dealer, '40s' AS age_band, 'F' AS gender, 'web_lead' AS acquired_via, DATE '2026-09-29' AS first_seen, 'LMULYT25I000I' AS web_lead_id, 'instagram' AS first_touch_source),
  STRUCT('C942B748793AB' AS customer_id, 'seoul' AS region, '서울 강남 전시장' AS home_dealer, '40s' AS age_band, 'M' AS gender, 'web_lead' AS acquired_via, DATE '2026-09-29' AS first_seen, 'LMULYTENXZBRY' AS web_lead_id, 'youtube' AS first_touch_source),
  STRUCT('C3447D4CBAC50' AS customer_id, 'gyeonggi' AS region, '분당 판교 전시장' AS home_dealer, '30s' AS age_band, 'F' AS gender, 'web_lead' AS acquired_via, DATE '2026-09-29' AS first_seen, 'LMULYTR0TMXD5' AS web_lead_id, 'naver' AS first_touch_source),
  STRUCT('C9B5A3EDE9913' AS customer_id, 'daegu' AS region, '대구 수성 전시장' AS home_dealer, '40s' AS age_band, 'M' AS gender, 'walk_in' AS acquired_via, DATE '2026-09-17' AS first_seen, CAST(NULL AS STRING) AS web_lead_id, CAST(NULL AS STRING) AS first_touch_source),
  STRUCT('C403D445EFFC6' AS customer_id, 'gyeonggi' AS region, '분당 판교 전시장' AS home_dealer, '30s' AS age_band, 'M' AS gender, 'walk_in' AS acquired_via, DATE '2026-09-16' AS first_seen, CAST(NULL AS STRING) AS web_lead_id, CAST(NULL AS STRING) AS first_touch_source),
  STRUCT('CBE29943372B6' AS customer_id, 'daejeon' AS region, '대전 둔산 전시장' AS home_dealer, '60s+' AS age_band, 'M' AS gender, 'walk_in' AS acquired_via, DATE '2026-09-10' AS first_seen, CAST(NULL AS STRING) AS web_lead_id, CAST(NULL AS STRING) AS first_touch_source),
  STRUCT('C610BA75D086B' AS customer_id, 'gyeonggi' AS region, '분당 판교 전시장' AS home_dealer, '50s' AS age_band, 'F' AS gender, 'walk_in' AS acquired_via, DATE '2026-09-12' AS first_seen, CAST(NULL AS STRING) AS web_lead_id, CAST(NULL AS STRING) AS first_touch_source),
  STRUCT('C67418302B5BA' AS customer_id, 'daegu' AS region, '대구 수성 전시장' AS home_dealer, '30s' AS age_band, 'F' AS gender, 'walk_in' AS acquired_via, DATE '2026-09-09' AS first_seen, CAST(NULL AS STRING) AS web_lead_id, CAST(NULL AS STRING) AS first_touch_source),
  STRUCT('CE4FA8EAD9532' AS customer_id, 'busan' AS region, '부산 해운대 전시장' AS home_dealer, '30s' AS age_band, 'M' AS gender, 'walk_in' AS acquired_via, DATE '2026-09-12' AS first_seen, CAST(NULL AS STRING) AS web_lead_id, CAST(NULL AS STRING) AS first_touch_source),
  STRUCT('CDA1809C51C94' AS customer_id, 'gwangju' AS region, '광주 상무 전시장' AS home_dealer, '30s' AS age_band, 'F' AS gender, 'walk_in' AS acquired_via, DATE '2026-09-14' AS first_seen, CAST(NULL AS STRING) AS web_lead_id, CAST(NULL AS STRING) AS first_touch_source),
  STRUCT('C60F1A2548D16' AS customer_id, 'incheon' AS region, '인천 송도 전시장' AS home_dealer, '50s' AS age_band, 'M' AS gender, 'walk_in' AS acquired_via, DATE '2026-09-11' AS first_seen, CAST(NULL AS STRING) AS web_lead_id, CAST(NULL AS STRING) AS first_touch_source),
  STRUCT('CB15ED25361C9' AS customer_id, 'incheon' AS region, '인천 송도 전시장' AS home_dealer, '40s' AS age_band, 'F' AS gender, 'walk_in' AS acquired_via, DATE '2026-09-16' AS first_seen, CAST(NULL AS STRING) AS web_lead_id, CAST(NULL AS STRING) AS first_touch_source),
  STRUCT('CC57A955C929B' AS customer_id, 'busan' AS region, '부산 해운대 전시장' AS home_dealer, '40s' AS age_band, 'M' AS gender, 'walk_in' AS acquired_via, DATE '2026-09-17' AS first_seen, CAST(NULL AS STRING) AS web_lead_id, CAST(NULL AS STRING) AS first_touch_source),
  STRUCT('C02B32FB9CF09' AS customer_id, 'gyeonggi' AS region, '분당 판교 전시장' AS home_dealer, '40s' AS age_band, 'M' AS gender, 'walk_in' AS acquired_via, DATE '2026-09-12' AS first_seen, CAST(NULL AS STRING) AS web_lead_id, CAST(NULL AS STRING) AS first_touch_source),
  STRUCT('CE115526B6B26' AS customer_id, 'busan' AS region, '부산 해운대 전시장' AS home_dealer, '30s' AS age_band, 'F' AS gender, 'walk_in' AS acquired_via, DATE '2026-09-20' AS first_seen, CAST(NULL AS STRING) AS web_lead_id, CAST(NULL AS STRING) AS first_touch_source)
]);

CREATE OR REPLACE TABLE `toyomo-ga4.crm.dealer_test_drives` AS
SELECT * FROM UNNEST([
  STRUCT('TD00001' AS test_drive_id, 'C69CE05961B9B' AS customer_id, '서울 강남 전시장' AS dealer, 'ravon' AS model, DATE '2026-09-29' AS test_drive_date, '김대리' AS sales_rep, 5 AS satisfaction, 'LMUKY5ZZX0YLC' AS web_lead_id),
  STRUCT('TD00002' AS test_drive_id, 'C7B6B8E0B64FA' AS customer_id, '인천 송도 전시장' AS dealer, 'ravon' AS model, DATE '2026-10-02' AS test_drive_date, '김대리' AS sales_rep, 5 AS satisfaction, 'LMUKY6CUBAD8F' AS web_lead_id),
  STRUCT('TD00003' AS test_drive_id, 'CD9C798D966D5' AS customer_id, '서울 강남 전시장' AS dealer, 'prima' AS model, DATE '2026-10-05' AS test_drive_date, '김대리' AS sales_rep, 5 AS satisfaction, 'LMUKY8V339I56' AS web_lead_id),
  STRUCT('TD00004' AS test_drive_id, 'CF80E360C12E2' AS customer_id, '대구 수성 전시장' AS dealer, 'ravon' AS model, DATE '2026-10-09' AS test_drive_date, '이과장' AS sales_rep, 3 AS satisfaction, 'LMUKYAF4RZ2CA' AS web_lead_id),
  STRUCT('TD00005' AS test_drive_id, 'C712BAF74BDE1' AS customer_id, '대구 수성 전시장' AS dealer, 'ceres' AS model, DATE '2026-09-30' AS test_drive_date, '정사원' AS sales_rep, 3 AS satisfaction, 'LMUKYB8AQIHXV' AS web_lead_id),
  STRUCT('TD00006' AS test_drive_id, 'C57455088AC05' AS customer_id, '대구 수성 전시장' AS dealer, 'vento' AS model, DATE '2026-10-02' AS test_drive_date, '이과장' AS sales_rep, 5 AS satisfaction, 'LMUKYBYYVWIY5' AS web_lead_id),
  STRUCT('TD00007' AS test_drive_id, 'CB29B4D6B6DE9' AS customer_id, '분당 판교 전시장' AS dealer, 'ravon' AS model, DATE '2026-10-02' AS test_drive_date, '박주임' AS sales_rep, 4 AS satisfaction, 'LMULYNWDHRLZ2' AS web_lead_id),
  STRUCT('TD00008' AS test_drive_id, 'CB3BF0B266708' AS customer_id, '광주 상무 전시장' AS dealer, 'vento' AS model, DATE '2026-10-05' AS test_drive_date, '정사원' AS sales_rep, 4 AS satisfaction, 'LMULYRRXH7SQH' AS web_lead_id),
  STRUCT('TD00009' AS test_drive_id, 'C4053A83827FE' AS customer_id, '분당 판교 전시장' AS dealer, 'ravon' AS model, DATE '2026-10-04' AS test_drive_date, '강대리' AS sales_rep, 5 AS satisfaction, 'LMULYT25I000I' AS web_lead_id),
  STRUCT('TD00010' AS test_drive_id, 'C942B748793AB' AS customer_id, '서울 강남 전시장' AS dealer, 'prima' AS model, DATE '2026-10-10' AS test_drive_date, '박주임' AS sales_rep, 3 AS satisfaction, 'LMULYTENXZBRY' AS web_lead_id),
  STRUCT('TD00011' AS test_drive_id, 'C3447D4CBAC50' AS customer_id, '분당 판교 전시장' AS dealer, 'vento' AS model, DATE '2026-10-03' AS test_drive_date, '박주임' AS sales_rep, 4 AS satisfaction, 'LMULYTR0TMXD5' AS web_lead_id),
  STRUCT('TD00012' AS test_drive_id, 'C9B5A3EDE9913' AS customer_id, '대구 수성 전시장' AS dealer, 'prima' AS model, DATE '2026-09-17' AS test_drive_date, '강대리' AS sales_rep, 4 AS satisfaction, CAST(NULL AS STRING) AS web_lead_id),
  STRUCT('TD00013' AS test_drive_id, 'C403D445EFFC6' AS customer_id, '분당 판교 전시장' AS dealer, 'ravon' AS model, DATE '2026-09-16' AS test_drive_date, '박주임' AS sales_rep, 4 AS satisfaction, CAST(NULL AS STRING) AS web_lead_id),
  STRUCT('TD00014' AS test_drive_id, 'CBE29943372B6' AS customer_id, '대전 둔산 전시장' AS dealer, 'vento' AS model, DATE '2026-09-10' AS test_drive_date, '최팀장' AS sales_rep, 4 AS satisfaction, CAST(NULL AS STRING) AS web_lead_id),
  STRUCT('TD00015' AS test_drive_id, 'C610BA75D086B' AS customer_id, '분당 판교 전시장' AS dealer, 'ceres' AS model, DATE '2026-09-12' AS test_drive_date, '김대리' AS sales_rep, 5 AS satisfaction, CAST(NULL AS STRING) AS web_lead_id),
  STRUCT('TD00016' AS test_drive_id, 'C67418302B5BA' AS customer_id, '대구 수성 전시장' AS dealer, 'vento' AS model, DATE '2026-09-09' AS test_drive_date, '이과장' AS sales_rep, 5 AS satisfaction, CAST(NULL AS STRING) AS web_lead_id),
  STRUCT('TD00017' AS test_drive_id, 'CE4FA8EAD9532' AS customer_id, '부산 해운대 전시장' AS dealer, 'vento' AS model, DATE '2026-09-12' AS test_drive_date, '최팀장' AS sales_rep, 4 AS satisfaction, CAST(NULL AS STRING) AS web_lead_id),
  STRUCT('TD00018' AS test_drive_id, 'CDA1809C51C94' AS customer_id, '광주 상무 전시장' AS dealer, 'prima' AS model, DATE '2026-09-14' AS test_drive_date, '이과장' AS sales_rep, 5 AS satisfaction, CAST(NULL AS STRING) AS web_lead_id),
  STRUCT('TD00019' AS test_drive_id, 'C60F1A2548D16' AS customer_id, '인천 송도 전시장' AS dealer, 'ravon' AS model, DATE '2026-09-11' AS test_drive_date, '박주임' AS sales_rep, 5 AS satisfaction, CAST(NULL AS STRING) AS web_lead_id),
  STRUCT('TD00020' AS test_drive_id, 'CB15ED25361C9' AS customer_id, '인천 송도 전시장' AS dealer, 'vento' AS model, DATE '2026-09-16' AS test_drive_date, '강대리' AS sales_rep, 5 AS satisfaction, CAST(NULL AS STRING) AS web_lead_id),
  STRUCT('TD00021' AS test_drive_id, 'CC57A955C929B' AS customer_id, '부산 해운대 전시장' AS dealer, 'vento' AS model, DATE '2026-09-17' AS test_drive_date, '강대리' AS sales_rep, 5 AS satisfaction, CAST(NULL AS STRING) AS web_lead_id),
  STRUCT('TD00022' AS test_drive_id, 'C02B32FB9CF09' AS customer_id, '분당 판교 전시장' AS dealer, 'ravon' AS model, DATE '2026-09-12' AS test_drive_date, '박주임' AS sales_rep, 4 AS satisfaction, CAST(NULL AS STRING) AS web_lead_id),
  STRUCT('TD00023' AS test_drive_id, 'CE115526B6B26' AS customer_id, '부산 해운대 전시장' AS dealer, 'vento' AS model, DATE '2026-09-20' AS test_drive_date, '강대리' AS sales_rep, 5 AS satisfaction, CAST(NULL AS STRING) AS web_lead_id)
]);

CREATE OR REPLACE TABLE `toyomo-ga4.crm.contracts` AS
SELECT * FROM UNNEST([
  STRUCT('CT00001' AS contract_id, 'C69CE05961B9B' AS customer_id, DATE '2026-10-06' AS contract_date, '서울 강남 전시장' AS dealer, 'ravon' AS model, 'Signature' AS trim, 46300000 AS price, '김대리' AS sales_rep, 'cash' AS financing),
  STRUCT('CT00002' AS contract_id, 'C7B6B8E0B64FA' AS customer_id, DATE '2026-10-23' AS contract_date, '인천 송도 전시장' AS dealer, 'ravon' AS model, 'Signature' AS trim, 46300000 AS price, '김대리' AS sales_rep, 'lease' AS financing),
  STRUCT('CT00003' AS contract_id, 'CD9C798D966D5' AS customer_id, DATE '2026-10-23' AS contract_date, '서울 강남 전시장' AS dealer, 'prima' AS model, 'Premium' AS trim, 39200000 AS price, '김대리' AS sales_rep, 'cash' AS financing),
  STRUCT('CT00004' AS contract_id, 'C712BAF74BDE1' AS customer_id, DATE '2026-10-11' AS contract_date, '대구 수성 전시장' AS dealer, 'ceres' AS model, 'Premium' AS trim, 35300000 AS price, '정사원' AS sales_rep, 'loan' AS financing),
  STRUCT('CT00005' AS contract_id, 'C57455088AC05' AS customer_id, DATE '2026-10-13' AS contract_date, '대구 수성 전시장' AS dealer, 'vento' AS model, 'Premium' AS trim, 47600000 AS price, '이과장' AS sales_rep, 'lease' AS financing),
  STRUCT('CT00006' AS contract_id, 'C3447D4CBAC50' AS customer_id, DATE '2026-10-06' AS contract_date, '분당 판교 전시장' AS dealer, 'vento' AS model, 'Signature' AS trim, 50000000 AS price, '박주임' AS sales_rep, 'cash' AS financing),
  STRUCT('CT00007' AS contract_id, 'C9B5A3EDE9913' AS customer_id, DATE '2026-09-21' AS contract_date, '대구 수성 전시장' AS dealer, 'prima' AS model, 'Premium' AS trim, 39200000 AS price, '이과장' AS sales_rep, 'cash' AS financing),
  STRUCT('CT00008' AS contract_id, 'C403D445EFFC6' AS customer_id, DATE '2026-09-22' AS contract_date, '분당 판교 전시장' AS dealer, 'ravon' AS model, 'Signature' AS trim, 46300000 AS price, '정사원' AS sales_rep, 'lease' AS financing),
  STRUCT('CT00009' AS contract_id, 'CBE29943372B6' AS customer_id, DATE '2026-09-11' AS contract_date, '대전 둔산 전시장' AS dealer, 'vento' AS model, 'Premium' AS trim, 47600000 AS price, '이과장' AS sales_rep, 'cash' AS financing),
  STRUCT('CT00010' AS contract_id, 'CE4FA8EAD9532' AS customer_id, DATE '2026-09-24' AS contract_date, '부산 해운대 전시장' AS dealer, 'vento' AS model, 'Standard' AS trim, 45200000 AS price, '박주임' AS sales_rep, 'lease' AS financing),
  STRUCT('CT00011' AS contract_id, 'CB15ED25361C9' AS customer_id, DATE '2026-09-22' AS contract_date, '인천 송도 전시장' AS dealer, 'vento' AS model, 'Premium' AS trim, 47600000 AS price, '강대리' AS sales_rep, 'cash' AS financing),
  STRUCT('CT00012' AS contract_id, 'CE115526B6B26' AS customer_id, DATE '2026-09-27' AS contract_date, '부산 해운대 전시장' AS dealer, 'vento' AS model, 'Standard' AS trim, 45200000 AS price, '강대리' AS sales_rep, 'loan' AS financing)
]);
